# Generated by Django 2.2 on 2019-07-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_auto_20190731_0214'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
            ],
        ),
    ]
